---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fauzanmu/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r img $DEPLOYPATH
    - /bin/cp -r css $DEPLOYPATH
    - /bin/cp -r js $DEPLOYPATH
    - /bin/cp -r scss $DEPLOYPATH